// SUPER LOVABLE — background service worker (MV3)
importScripts('modules/device-identity-manager.js');
importScripts('modules/license-client.js');
importScripts('modules/lovable-sender.js');
importScripts('modules/queue-engine.js');
const LICENSE_ALARM='super_lovable_license_check', QUEUE_ALARM='super_lovable_queue_tick', VISUAL_KEY='slv2_visual_selection';
chrome.runtime.onInstalled.addListener(async(d)=>{if(typeof DeviceIdentityManager!=='undefined')await DeviceIdentityManager.ensure({reason:d.reason});bootLicense('instalação');});
chrome.runtime.onStartup.addListener(()=>bootLicense('início do navegador'));
async function bootLicense(){try{await LicenseClient.getDeviceId();await chrome.alarms.create(LICENSE_ALARM,{periodInMinutes:720});const s=await LicenseClient.getStoredLicense();if(s.license_token)await LicenseClient.validateLicense();await broadcastLicense();}catch(e){console.warn('Licença: verificação inicial indisponível.',e.message);}}
chrome.alarms.onAlarm.addListener(async(a)=>{if(a.name===QUEUE_ALARM){QueueEngine.tick().catch(()=>{});return;}if(a.name!==LICENSE_ALARM)return;const s=await LicenseClient.getStoredLicense();if(!s.license_token)return;await LicenseClient.validateLicense();await broadcastLicense();});
async function broadcastLicense(){const s=await LicenseClient.getStoredLicense(),active=LicenseClient.hasActiveLicense(s);try{await chrome.runtime.sendMessage({action:'licenseState',active});}catch(e){}try{const tabs=await chrome.tabs.query({url:['https://lovable.dev/*','https://*.lovable.dev/*']});for(const t of tabs)chrome.tabs.sendMessage(t.id,{action:'licenseState',active},()=>chrome.runtime.lastError);}catch(e){}return active;}
async function licenseGate(){const r=await LicenseClient.ensureFresh();return r.ok?{allowed:true}:{allowed:false,reason:r.message||LicenseClient.REASONS.none};}
const PROTECTED=new Set(['uploadToStorage','superLovableForward','superLovableTool','SUPER_LOVABLE_SUBMIT_PROMPT','SUPER_LOVABLE_ENQUEUE_PROMPT']);
const QUEUE_CONTROL={SUPER_LOVABLE_QUEUE_SNAPSHOT:()=>QueueEngine.snapshot(),SUPER_LOVABLE_QUEUE_TICK:()=>QueueEngine.tick().then(()=>({success:true})),SUPER_LOVABLE_QUEUE_PAUSE:()=>QueueEngine.pause().then(()=>({success:true})),SUPER_LOVABLE_QUEUE_RESUME:()=>QueueEngine.resume().then(()=>({success:true})),SUPER_LOVABLE_QUEUE_CONFIRM:()=>QueueEngine.confirmCompletion(),SUPER_LOVABLE_QUEUE_KEEP_WAITING:()=>QueueEngine.keepWaiting(),SUPER_LOVABLE_QUEUE_RETRY:d=>QueueEngine.retry(d.id).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_SKIP:d=>QueueEngine.skip(d.id).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_EDIT:d=>QueueEngine.edit(d.id,d.text).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_SEND_NOW:d=>QueueEngine.sendNow(d.id),SUPER_LOVABLE_QUEUE_SET_MODE:d=>QueueEngine.setMode(d.id,d.mode),SUPER_LOVABLE_QUEUE_REMOVE:d=>QueueEngine.remove(d.id).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_MOVE:d=>QueueEngine.moveTo(d.id,d.index).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_DUPLICATE:d=>QueueEngine.duplicate(d.id).then(()=>({success:true})),SUPER_LOVABLE_QUEUE_CLEAR_DONE:()=>QueueEngine.clearDone().then(()=>({success:true})),SUPER_LOVABLE_QUEUE_CLEAR_ALL:()=>QueueEngine.clearAll().then(()=>({success:true})),SUPER_LOVABLE_EXECUTION_STATE:d=>QueueEngine.getLovableExecutionState(d&&d.projectId)};
chrome.runtime.onMessage.addListener((request,_sender,sendResponse)=>{const action=request.action||request.type;
 if(action==='SLV2_VISUAL_SELECTION'){chrome.storage.local.set({[VISUAL_KEY]:request.selection||null}).then(()=>{try{chrome.runtime.sendMessage({action:'SLV2_VISUAL_SELECTION_UPDATED',selection:request.selection||null});}catch(e){}sendResponse({success:true});});return true;}
 if(action==='SLV2_GET_VISUAL_SELECTION'){chrome.storage.local.get(VISUAL_KEY).then(r=>sendResponse({success:true,selection:r[VISUAL_KEY]||null}));return true;}
 if(action==='SLV2_CLEAR_VISUAL_SELECTION'){chrome.storage.local.remove(VISUAL_KEY).then(()=>sendResponse({success:true}));return true;}
 if(action==='licenseChanged'){bootLicense().then(()=>sendResponse({success:true}));return true;}
 if(action==='licenseStatus'){LicenseClient.getStoredLicense().then(s=>sendResponse({success:true,active:LicenseClient.hasActiveLicense(s),status:s.status}));return true;}
 if(QUEUE_CONTROL[action]){QUEUE_CONTROL[action](request.data||{}).then(r=>sendResponse({success:true,...r})).catch(e=>sendResponse({success:false,error:e.message}));return true;}
 if(PROTECTED.has(action)){licenseGate().then(g=>{if(!g.allowed)return sendResponse({success:false,blocked:true,error:g.reason});handleProtected({...request,action}).then(sendResponse).catch(e=>sendResponse({success:false,error:e.message}));});return true;}
 if(action==='apiFetch'){handleApiFetch(request.data).then(sendResponse).catch(e=>sendResponse({success:false,error:e.message}));return true;}return false;});
async function handleProtected(r){if(r.action==='uploadToStorage')return handleUpload(r.data);if(r.action==='superLovableForward')return handleForward(r.data);if(r.action==='SUPER_LOVABLE_SUBMIT_PROMPT')return QueueEngine.submitOrQueuePrompt(r.data||{});if(r.action==='SUPER_LOVABLE_ENQUEUE_PROMPT')return QueueEngine.submitOrQueuePrompt({...r.data,forceQueue:true});if(r.action==='superLovableTool'){await chrome.storage.local.set({super_lovable_pending_tool:r.data});return{success:true};}return{success:false,error:'Ação desconhecida.'};}
async function handleUpload({url,headers,body,byteLength}){const bytes=new Uint8Array(body);if(byteLength&&bytes.byteLength!==byteLength)throw new Error(`Bytes perdidos no transporte (${bytes.byteLength} de ${byteLength}).`);const res=await fetch(url,{method:'PUT',headers,body:bytes});if(!res.ok){const text=await res.text().catch(()=>'');throw new Error(`Upload GCS falhou: ${res.status} ${text.slice(0,200)}`);}return{success:true,status:res.status,bytes:bytes.byteLength};}
async function handleApiFetch({url,method,headers,body}){const res=await fetch(url,{method:method||'GET',headers,body,credentials:'include'});const text=await res.text();return{success:res.ok,status:res.status,body:text};}
async function handleForward({text,projectId,origin}){const res=await QueueEngine.submitOrQueuePrompt({text,projectId,source:origin==='native_toolbar'?'native_toolbar':'native_chat',attachments:[]});const snap=await QueueEngine.snapshot();return{...res,queueSize:snap.summary.total,position:res.position||snap.summary.total};}
bootLicense();chrome.alarms.create(QUEUE_ALARM,{periodInMinutes:0.5});QueueEngine.scheduleTick(1500);
