/* SUPER LOVABLE V2 — sessão de licença */
import { getOrCreateDeviceIdentity } from './device-identity.js';
export const LICENSE_STATES=Object.freeze({BOOTING:'booting',ACTIVE_CACHED:'active_cached',ACTIVE_VERIFIED:'active_verified',ACTIVATION_REQUIRED:'activation_required',EXPIRED:'expired',DEVICE_LIMIT:'device_limit',REVOKED:'revoked',OFFLINE_GRACE:'offline_grace',ERROR:'error'});
const STORAGE_KEY='slv2_license_session',DEFAULT_CACHE_TTL_MS=10*60*1000,DEFAULT_OFFLINE_GRACE_MS=24*60*60*1000;
function area(){if(!globalThis.chrome?.storage?.local)throw new Error('chrome.storage.local indisponível');return globalThis.chrome.storage.local;}
function storageGet(key){return new Promise((resolve,reject)=>area().get(key,r=>{const e=globalThis.chrome?.runtime?.lastError;e?reject(new Error(e.message)):resolve(r?.[key]||null);}));}
function storageSet(value){return new Promise((resolve,reject)=>area().set({[STORAGE_KEY]:value},()=>{const e=globalThis.chrome?.runtime?.lastError;e?reject(new Error(e.message)):resolve();}));}
const now=()=>Date.now();function parseTime(v){if(!v)return null;const p=new Date(v).getTime();return Number.isFinite(p)?p:null;}function expired(s,at=now()){const e=parseTime(s?.expiresAt);return e!==null&&e<=at;}function fresh(s,ttl,at=now()){const v=parseTime(s?.verifiedAt);return v!==null&&at-v<=ttl;}function grace(s,g,at=now()){const v=parseTime(s?.verifiedAt);return v!==null&&!expired(s,at)&&at-v<=g;}
function normalizeState(p){const s=String(p?.status||'').toLowerCase();if(['active','valid','enabled'].includes(s))return LICENSE_STATES.ACTIVE_VERIFIED;if(s==='expired')return LICENSE_STATES.EXPIRED;if(['device_limit','device-limit','limit_reached'].includes(s))return LICENSE_STATES.DEVICE_LIMIT;if(['revoked','blocked','disabled'].includes(s))return LICENSE_STATES.REVOKED;return LICENSE_STATES.ACTIVATION_REQUIRED;}
function publicSession(s,state,source){return Object.freeze({state,source,licenseKey:s?.licenseKey||null,plan:s?.plan||null,role:String(s?.role||'user').toLowerCase(),expiresAt:s?.expiresAt||null,verifiedAt:s?.verifiedAt||null,deviceId:s?.deviceId||null,message:s?.message||null});}
export class LicenseSessionManager{constructor({validateRemote,cacheTtlMs=DEFAULT_CACHE_TTL_MS,offlineGraceMs=DEFAULT_OFFLINE_GRACE_MS}={}){if(typeof validateRemote!=='function')throw new TypeError('validateRemote deve ser uma função');this.validateRemote=validateRemote;this.cacheTtlMs=cacheTtlMs;this.offlineGraceMs=offlineGraceMs;}async readCachedSession(){return storageGet(STORAGE_KEY);}async bootstrap(){const d=await getOrCreateDeviceIdentity(),c=await this.readCachedSession();if(!c?.licenseKey)return publicSession({deviceId:d.id},LICENSE_STATES.ACTIVATION_REQUIRED,'no-cache');if(expired(c))return publicSession(c,LICENSE_STATES.EXPIRED,'cache-expired');if(c.deviceId&&c.deviceId!==d.id)return this.verify({...c,deviceId:d.id},{reason:'device-migration'});if(fresh(c,this.cacheTtlMs)){void this.verify(c,{reason:'background-refresh',silent:true});return publicSession(c,LICENSE_STATES.ACTIVE_CACHED,'fresh-cache');}return this.verify(c,{reason:'cache-stale'});}async activate(key){const k=String(key||'').trim().toUpperCase();if(!k)return publicSession(null,LICENSE_STATES.ACTIVATION_REQUIRED,'empty-key');const d=await getOrCreateDeviceIdentity();return this.verify({licenseKey:k,deviceId:d.id},{reason:'activation'});}async verify(session,{reason='manual',silent=false}={}){const d=await getOrCreateDeviceIdentity(),request={licenseKey:session.licenseKey,deviceId:d.id,installationId:d.id,extensionVersion:globalThis.chrome?.runtime?.getManifest?.().version||'unknown',reason};try{const r=await this.validateRemote(request),state=normalizeState(r),next={licenseKey:session.licenseKey,deviceId:d.id,plan:r?.plan||session?.plan||null,role:String(r?.role||session?.role||'user').toLowerCase(),expiresAt:r?.expiresAt||session?.expiresAt||null,verifiedAt:new Date().toISOString(),serverDeviceId:r?.deviceId||null,message:r?.message||null,state};await storageSet(next);return publicSession(next,state,'remote');}catch(error){const c=await this.readCachedSession();if(c?.licenseKey===session.licenseKey&&grace(c,this.offlineGraceMs))return publicSession({...c,message:'Validação temporariamente indisponível.'},LICENSE_STATES.OFFLINE_GRACE,silent?'background-offline':'offline-grace');return publicSession({...session,deviceId:d.id,message:error?.message||'Falha ao validar licença.'},LICENSE_STATES.ERROR,'remote-error');}}async clearLocalSession(){await storageSet(null);}}
export function shouldShowMainInterface(s){return[LICENSE_STATES.ACTIVE_CACHED,LICENSE_STATES.ACTIVE_VERIFIED,LICENSE_STATES.OFFLINE_GRACE].includes(s);}export function shouldShowActivation(s){return[LICENSE_STATES.ACTIVATION_REQUIRED,LICENSE_STATES.EXPIRED,LICENSE_STATES.DEVICE_LIMIT,LICENSE_STATES.REVOKED,LICENSE_STATES.ERROR].includes(s);}
