/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicValidateLicenseRouteImport } from './routes/api/public/validate-license'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'
import { Route as ApiPublicRecoverDeviceRouteImport } from './routes/api/public/recover-device'
import { Route as ApiPublicOptimizePromptRouteImport } from './routes/api/public/optimize-prompt'
import { Route as ApiPublicDeactivateDeviceRouteImport } from './routes/api/public/deactivate-device'
import { Route as ApiPublicActivateLicenseRouteImport } from './routes/api/public/activate-license'
import { Route as ApiGithubStatusRouteImport } from './routes/api/github/status'
import { Route as ApiGithubRepositoriesRouteImport } from './routes/api/github/repositories'
import { Route as ApiGithubDisconnectRouteImport } from './routes/api/github/disconnect'
import { Route as ApiGithubConnectRouteImport } from './routes/api/github/connect'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiPublicWebhooksSalesRouteImport } from './routes/api/public/webhooks/sales'
import { Route as ApiPublicWebhooksEnsinaflixRouteImport } from './routes/api/public/webhooks/ensinaflix'
import { Route as ApiPublicProjectsWatermarkStatusRouteImport } from './routes/api/public/projects/watermark-status'
import { Route as ApiPublicProjectsRemoveWatermarkRouteImport } from './routes/api/public/projects/remove-watermark'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicValidateLicenseRoute =
  ApiPublicValidateLicenseRouteImport.update({
    id: '/api/public/validate-license',
    path: '/api/public/validate-license',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecoverDeviceRoute = ApiPublicRecoverDeviceRouteImport.update({
  id: '/api/public/recover-device',
  path: '/api/public/recover-device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOptimizePromptRoute = ApiPublicOptimizePromptRouteImport.update({
  id: '/api/public/optimize-prompt',
  path: '/api/public/optimize-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeactivateDeviceRoute =
  ApiPublicDeactivateDeviceRouteImport.update({
    id: '/api/public/deactivate-device',
    path: '/api/public/deactivate-device',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivateLicenseRoute =
  ApiPublicActivateLicenseRouteImport.update({
    id: '/api/public/activate-license',
    path: '/api/public/activate-license',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubStatusRoute = ApiGithubStatusRouteImport.update({
  id: '/api/github/status',
  path: '/api/github/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubRepositoriesRoute = ApiGithubRepositoriesRouteImport.update({
  id: '/api/github/repositories',
  path: '/api/github/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubDisconnectRoute = ApiGithubDisconnectRouteImport.update({
  id: '/api/github/disconnect',
  path: '/api/github/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubConnectRoute = ApiGithubConnectRouteImport.update({
  id: '/api/github/connect',
  path: '/api/github/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSalesRoute = ApiPublicWebhooksSalesRouteImport.update({
  id: '/api/public/webhooks/sales',
  path: '/api/public/webhooks/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksEnsinaflixRoute =
  ApiPublicWebhooksEnsinaflixRouteImport.update({
    id: '/api/public/webhooks/ensinaflix',
    path: '/api/public/webhooks/ensinaflix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProjectsWatermarkStatusRoute =
  ApiPublicProjectsWatermarkStatusRouteImport.update({
    id: '/api/public/projects/watermark-status',
    path: '/api/public/projects/watermark-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProjectsRemoveWatermarkRoute =
  ApiPublicProjectsRemoveWatermarkRouteImport.update({
    id: '/api/public/projects/remove-watermark',
    path: '/api/public/projects/remove-watermark',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/disconnect': typeof ApiGithubDisconnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/optimize-prompt': typeof ApiPublicOptimizePromptRoute
  '/api/public/recover-device': typeof ApiPublicRecoverDeviceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/projects/remove-watermark': typeof ApiPublicProjectsRemoveWatermarkRoute
  '/api/public/projects/watermark-status': typeof ApiPublicProjectsWatermarkStatusRoute
  '/api/public/webhooks/ensinaflix': typeof ApiPublicWebhooksEnsinaflixRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/disconnect': typeof ApiGithubDisconnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/optimize-prompt': typeof ApiPublicOptimizePromptRoute
  '/api/public/recover-device': typeof ApiPublicRecoverDeviceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/projects/remove-watermark': typeof ApiPublicProjectsRemoveWatermarkRoute
  '/api/public/projects/watermark-status': typeof ApiPublicProjectsWatermarkStatusRoute
  '/api/public/webhooks/ensinaflix': typeof ApiPublicWebhooksEnsinaflixRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/api/github/connect': typeof ApiGithubConnectRoute
  '/api/github/disconnect': typeof ApiGithubDisconnectRoute
  '/api/github/repositories': typeof ApiGithubRepositoriesRoute
  '/api/github/status': typeof ApiGithubStatusRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/optimize-prompt': typeof ApiPublicOptimizePromptRoute
  '/api/public/recover-device': typeof ApiPublicRecoverDeviceRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/projects/remove-watermark': typeof ApiPublicProjectsRemoveWatermarkRoute
  '/api/public/projects/watermark-status': typeof ApiPublicProjectsWatermarkStatusRoute
  '/api/public/webhooks/ensinaflix': typeof ApiPublicWebhooksEnsinaflixRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/disconnect'
    | '/api/github/repositories'
    | '/api/github/status'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/optimize-prompt'
    | '/api/public/recover-device'
    | '/api/public/transcribe'
    | '/api/public/validate-license'
    | '/api/public/github/callback'
    | '/api/public/projects/remove-watermark'
    | '/api/public/projects/watermark-status'
    | '/api/public/webhooks/ensinaflix'
    | '/api/public/webhooks/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/disconnect'
    | '/api/github/repositories'
    | '/api/github/status'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/optimize-prompt'
    | '/api/public/recover-device'
    | '/api/public/transcribe'
    | '/api/public/validate-license'
    | '/api/public/github/callback'
    | '/api/public/projects/remove-watermark'
    | '/api/public/projects/watermark-status'
    | '/api/public/webhooks/ensinaflix'
    | '/api/public/webhooks/sales'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/api/github/callback'
    | '/api/github/connect'
    | '/api/github/disconnect'
    | '/api/github/repositories'
    | '/api/github/status'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/optimize-prompt'
    | '/api/public/recover-device'
    | '/api/public/transcribe'
    | '/api/public/validate-license'
    | '/api/public/github/callback'
    | '/api/public/projects/remove-watermark'
    | '/api/public/projects/watermark-status'
    | '/api/public/webhooks/ensinaflix'
    | '/api/public/webhooks/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiGithubConnectRoute: typeof ApiGithubConnectRoute
  ApiGithubDisconnectRoute: typeof ApiGithubDisconnectRoute
  ApiGithubRepositoriesRoute: typeof ApiGithubRepositoriesRoute
  ApiGithubStatusRoute: typeof ApiGithubStatusRoute
  ApiPublicActivateLicenseRoute: typeof ApiPublicActivateLicenseRoute
  ApiPublicDeactivateDeviceRoute: typeof ApiPublicDeactivateDeviceRoute
  ApiPublicOptimizePromptRoute: typeof ApiPublicOptimizePromptRoute
  ApiPublicRecoverDeviceRoute: typeof ApiPublicRecoverDeviceRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
  ApiPublicValidateLicenseRoute: typeof ApiPublicValidateLicenseRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
  ApiPublicProjectsRemoveWatermarkRoute: typeof ApiPublicProjectsRemoveWatermarkRoute
  ApiPublicProjectsWatermarkStatusRoute: typeof ApiPublicProjectsWatermarkStatusRoute
  ApiPublicWebhooksEnsinaflixRoute: typeof ApiPublicWebhooksEnsinaflixRoute
  ApiPublicWebhooksSalesRoute: typeof ApiPublicWebhooksSalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/validate-license': {
      id: '/api/public/validate-license'
      path: '/api/public/validate-license'
      fullPath: '/api/public/validate-license'
      preLoaderRoute: typeof ApiPublicValidateLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recover-device': {
      id: '/api/public/recover-device'
      path: '/api/public/recover-device'
      fullPath: '/api/public/recover-device'
      preLoaderRoute: typeof ApiPublicRecoverDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/optimize-prompt': {
      id: '/api/public/optimize-prompt'
      path: '/api/public/optimize-prompt'
      fullPath: '/api/public/optimize-prompt'
      preLoaderRoute: typeof ApiPublicOptimizePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deactivate-device': {
      id: '/api/public/deactivate-device'
      path: '/api/public/deactivate-device'
      fullPath: '/api/public/deactivate-device'
      preLoaderRoute: typeof ApiPublicDeactivateDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate-license': {
      id: '/api/public/activate-license'
      path: '/api/public/activate-license'
      fullPath: '/api/public/activate-license'
      preLoaderRoute: typeof ApiPublicActivateLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/status': {
      id: '/api/github/status'
      path: '/api/github/status'
      fullPath: '/api/github/status'
      preLoaderRoute: typeof ApiGithubStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/repositories': {
      id: '/api/github/repositories'
      path: '/api/github/repositories'
      fullPath: '/api/github/repositories'
      preLoaderRoute: typeof ApiGithubRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/disconnect': {
      id: '/api/github/disconnect'
      path: '/api/github/disconnect'
      fullPath: '/api/github/disconnect'
      preLoaderRoute: typeof ApiGithubDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/connect': {
      id: '/api/github/connect'
      path: '/api/github/connect'
      fullPath: '/api/github/connect'
      preLoaderRoute: typeof ApiGithubConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/sales': {
      id: '/api/public/webhooks/sales'
      path: '/api/public/webhooks/sales'
      fullPath: '/api/public/webhooks/sales'
      preLoaderRoute: typeof ApiPublicWebhooksSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ensinaflix': {
      id: '/api/public/webhooks/ensinaflix'
      path: '/api/public/webhooks/ensinaflix'
      fullPath: '/api/public/webhooks/ensinaflix'
      preLoaderRoute: typeof ApiPublicWebhooksEnsinaflixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/projects/watermark-status': {
      id: '/api/public/projects/watermark-status'
      path: '/api/public/projects/watermark-status'
      fullPath: '/api/public/projects/watermark-status'
      preLoaderRoute: typeof ApiPublicProjectsWatermarkStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/projects/remove-watermark': {
      id: '/api/public/projects/remove-watermark'
      path: '/api/public/projects/remove-watermark'
      fullPath: '/api/public/projects/remove-watermark'
      preLoaderRoute: typeof ApiPublicProjectsRemoveWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiGithubConnectRoute: ApiGithubConnectRoute,
  ApiGithubDisconnectRoute: ApiGithubDisconnectRoute,
  ApiGithubRepositoriesRoute: ApiGithubRepositoriesRoute,
  ApiGithubStatusRoute: ApiGithubStatusRoute,
  ApiPublicActivateLicenseRoute: ApiPublicActivateLicenseRoute,
  ApiPublicDeactivateDeviceRoute: ApiPublicDeactivateDeviceRoute,
  ApiPublicOptimizePromptRoute: ApiPublicOptimizePromptRoute,
  ApiPublicRecoverDeviceRoute: ApiPublicRecoverDeviceRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
  ApiPublicValidateLicenseRoute: ApiPublicValidateLicenseRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
  ApiPublicProjectsRemoveWatermarkRoute: ApiPublicProjectsRemoveWatermarkRoute,
  ApiPublicProjectsWatermarkStatusRoute: ApiPublicProjectsWatermarkStatusRoute,
  ApiPublicWebhooksEnsinaflixRoute: ApiPublicWebhooksEnsinaflixRoute,
  ApiPublicWebhooksSalesRoute: ApiPublicWebhooksSalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
