/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicValidateLicenseRouteImport } from './routes/api/public/validate-license'
import { Route as ApiPublicDeactivateDeviceRouteImport } from './routes/api/public/deactivate-device'
import { Route as ApiPublicActivateLicenseRouteImport } from './routes/api/public/activate-license'
import { Route as ApiPublicWebhooksSalesRouteImport } from './routes/api/public/webhooks/sales'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicValidateLicenseRoute =
  ApiPublicValidateLicenseRouteImport.update({
    id: '/api/public/validate-license',
    path: '/api/public/validate-license',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeactivateDeviceRoute =
  ApiPublicDeactivateDeviceRouteImport.update({
    id: '/api/public/deactivate-device',
    path: '/api/public/deactivate-device',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicActivateLicenseRoute =
  ApiPublicActivateLicenseRouteImport.update({
    id: '/api/public/activate-license',
    path: '/api/public/activate-license',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksSalesRoute = ApiPublicWebhooksSalesRouteImport.update({
  id: '/api/public/webhooks/sales',
  path: '/api/public/webhooks/sales',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/activate-license': typeof ApiPublicActivateLicenseRoute
  '/api/public/deactivate-device': typeof ApiPublicDeactivateDeviceRoute
  '/api/public/validate-license': typeof ApiPublicValidateLicenseRoute
  '/api/public/webhooks/sales': typeof ApiPublicWebhooksSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/validate-license'
    | '/api/public/webhooks/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/validate-license'
    | '/api/public/webhooks/sales'
  id:
    | '__root__'
    | '/'
    | '/api/public/activate-license'
    | '/api/public/deactivate-device'
    | '/api/public/validate-license'
    | '/api/public/webhooks/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicActivateLicenseRoute: typeof ApiPublicActivateLicenseRoute
  ApiPublicDeactivateDeviceRoute: typeof ApiPublicDeactivateDeviceRoute
  ApiPublicValidateLicenseRoute: typeof ApiPublicValidateLicenseRoute
  ApiPublicWebhooksSalesRoute: typeof ApiPublicWebhooksSalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/validate-license': {
      id: '/api/public/validate-license'
      path: '/api/public/validate-license'
      fullPath: '/api/public/validate-license'
      preLoaderRoute: typeof ApiPublicValidateLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deactivate-device': {
      id: '/api/public/deactivate-device'
      path: '/api/public/deactivate-device'
      fullPath: '/api/public/deactivate-device'
      preLoaderRoute: typeof ApiPublicDeactivateDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/activate-license': {
      id: '/api/public/activate-license'
      path: '/api/public/activate-license'
      fullPath: '/api/public/activate-license'
      preLoaderRoute: typeof ApiPublicActivateLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/sales': {
      id: '/api/public/webhooks/sales'
      path: '/api/public/webhooks/sales'
      fullPath: '/api/public/webhooks/sales'
      preLoaderRoute: typeof ApiPublicWebhooksSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicActivateLicenseRoute: ApiPublicActivateLicenseRoute,
  ApiPublicDeactivateDeviceRoute: ApiPublicDeactivateDeviceRoute,
  ApiPublicValidateLicenseRoute: ApiPublicValidateLicenseRoute,
  ApiPublicWebhooksSalesRoute: ApiPublicWebhooksSalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
